CREATE FUNCTION "SPLIT_STRING" 
( 
	v_INPUT_STRING VARCHAR(5000),	
	v_SPLIT_CHARACTER VARCHAR(5000)  DEFAULT ';'
) 
RETURNS TABLE
(
	"OUTPUT_SPLIT" VARCHAR(5000)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER AS
BEGIN
	DECLARE INPUT_STRING VARCHAR(5000) = v_INPUT_STRING || v_SPLIT_CHARACTER;
	DECLARE COUNTER INT := 1;
	SPLIT_VALUES = SELECT SUBSTR_BEFORE(:INPUT_STRING, v_SPLIT_CHARACTER) SINGLE_VAL FROM DUMMY;	
	SELECT SUBSTR_AFTER(:INPUT_STRING, v_SPLIT_CHARACTER) || v_SPLIT_CHARACTER INTO INPUT_STRING FROM DUMMY;
	
	WHILE( LENGTH(:INPUT_STRING) > 0 )	
	DO
	
	   SPLIT_VALUES =	
	   
	   				SELECT SUBSTR_BEFORE(:INPUT_STRING,v_SPLIT_CHARACTER) SINGLE_VAL FROM DUMMY				   
					   UNION 	   
					SELECT SINGLE_VAL FROM :SPLIT_VALUES;
	
	   SELECT SUBSTR_AFTER(:INPUT_STRING,v_SPLIT_CHARACTER) INTO INPUT_STRING FROM DUMMY;
	   	
	END WHILE;
	
	RETURN
	
	SELECT SINGLE_VAL AS "OUTPUT_SPLIT" FROM :SPLIT_VALUES where SINGLE_VAL <>''; 

END
