CREATE TABLE "tb_Addon_Config"
(
	"ConfigKey" NVARCHAR(30),
	"ConfigValue" NVARCHAR(255)
)
INSERT INTO "tb_Addon_Config" VALUES('Schema', 'PMP_QAS_SP2')
INSERT INTO "tb_Addon_Config" VALUES('APIVTB', 'https://api-uat.vietinbank.vn')
INSERT INTO "tb_Addon_Config" VALUES('InquiryVTB', '/vtb-api-uat/development/erp/v1/statement/inquiry')
INSERT INTO "tb_Addon_Config" VALUES('RateVTB', 'vtb-api-uat/development/v1/fxrate/ForeignExchangeRate_Inq')
INSERT INTO "tb_Addon_Config" VALUES('TransferVTB', '/vtb-api-uat/development/erp/v1/payment/transfer')
INSERT INTO "tb_Addon_Config" VALUES('TransferInqVTB', '/vtb-api-uat/development/erp/v1/payment/transferInq')
INSERT INTO "tb_Addon_Config" VALUES('ClientIDVTB', 'fbbf1989a3ad0de68446317f5f104df0')
INSERT INTO "tb_Addon_Config" VALUES('ClientSecretVTB', '2cd7b943f4d7c5115d44b81487497ae3')
INSERT INTO "tb_Addon_Config" VALUES('USER_APPROVE', 'pymepharco_pheduyet')
INSERT INTO "tb_Addon_Config" VALUES('USER_CREATE', 'pymepharco_taodien')
INSERT INTO "tb_Addon_Config" VALUES('ProviderId', 'PYMEPHARCO')
INSERT INTO "tb_Addon_Config" VALUES('MerchantId', '')
INSERT INTO "tb_Addon_Config" VALUES('ClientIP', '172.31.131.13')

INSERT INTO "tb_Addon_Config" VALUES('APILinkBIDV', 'https://www.bidv.net:9303')
INSERT INTO "tb_Addon_Config" VALUES('InquiryBIDV', '/bidvorg/service/open-banking/inquire-account-transaction/v1')
INSERT INTO "tb_Addon_Config" VALUES('AuthenBIDV', '/bidvorg/service/ibank-oauth/oauth2/token')
INSERT INTO "tb_Addon_Config" VALUES('ChannelBIDVAPI', 'IERP')
INSERT INTO "tb_Addon_Config" VALUES('UserAgentIDVAPI', 'IERP')
INSERT INTO "tb_Addon_Config" VALUES('SymmetricKey', '2094508740466af766392a869e92ac81229e15ec3e75b0476d8fbdbc9d924f65')
INSERT INTO "tb_Addon_Config" VALUES('ClientIDBIDV', 'df616d171dae4974042d4d95577c05de')
INSERT INTO "tb_Addon_Config" VALUES('ClientSecretBIDV', '9adc6d5f750dcdfc898c74aec2d0e0c7')
INSERT INTO "tb_Addon_Config" VALUES('URL_Redirect', 'https://azstvntstsapb1db:50000/b1s/v1/BIDV_TEST')
INSERT INTO "tb_Addon_Config" VALUES('TransferBIDV', '/bidvorg/service/open-banking/domestic-payment/v1')
INSERT INTO "tb_Addon_Config" VALUES('APILinkPY', 'https://bizsandbox.payoo.com.vn')
INSERT INTO "tb_Addon_Config" VALUES('SettlementTransactionsLink', '/BusinessRestAPI.svc/GetSettlementTransactions')
INSERT INTO "tb_Addon_Config" VALUES('APIUsernamePY', 'SB_Stada_BizAPI')
INSERT INTO "tb_Addon_Config" VALUES('APIPasswordPY', '9qW0k9/5khmSqdOE')
INSERT INTO "tb_Addon_Config" VALUES('APISignaturePY', 'U5E0ykWrsQSqkjS6xR+Qnj3cbuNUi8YgSC2r6/BcXrpdcjOx6XYh7XNjQf806Yay')
INSERT INTO "tb_Addon_Config" VALUES('ChecksumKeyPY', 'NzlkNTJmZDBhMjcyNDM0MjBkZWQ4NDI0ODNjYjY2YTI=')
	   